BirthdayApp/ViewModels/CollectViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using AppModels;

namespace BirthdayApp.ViewModels
{
    public class CollectUserItem
    {
        public string UserName { get; set; }
        public bool GaveMoney { get; set; }
    }

    public class RadioGiftItem
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int Rating { get; set; }
        public bool Checked { get; set; }
    }

    public class CollectViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public int OwnerId { get; set; }
        public int RecipientId { get; set; }
        public string OwnerName { get; set; }
        public string RecipientName { get; set; }
        public string Description { get; set; }
        public bool IsConfirmed { get; set; }
        public int Amount { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateOfInitiative { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateOfAdd { get; set; }
        public RadioGiftItem Gift { get; set; }
        public List<RadioGiftItem> RadioGiftItems { get; set; }
        public List<CollectUserItem> Users { get; set; }
        public bool PossibilityEditCollectGift { get; set; }
        public string GiftName { get; set;}
        public double AmountPerPerson { get; set; }
    }
}

BirthdayApp/ViewModels/Collects.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BirthdayApp.ViewModels
{
    public class CollectViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int OwnerId { get; set; }
        public int RecipientId { get; set; }
        public string OwnerName { get; set; }
        public string RecipientName { get; set; }
        public string Description { get; set; }
        [DataType(DataType.Currency)]
        [RegularExpression("^[0-9]{0,99999}$", ErrorMessage = "Value must be a natural number")]
        public int Amount { get; set; }
        public bool IsConfirmed { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateOfInitiative { get; set; }
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateOfAdd { get; set; }
    }
}

BirthdayApp/Controllers/CollectGiftsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppModels;
using BirthdayApp.Models;
using Microsoft.AspNet.Identity;
using BirthdayApp.AppService;

namespace BirthdayApp.Controllers
{
    public class CollectGiftsController : CommonController
    {
        public ActionResult Index(int id)
        {
            using (var collectService = new CollectsService())
            {
                ViewBag.collectId = id;
                var collectionsGifts = collectService.GetCollectsGiftsIndex(id);
                return View(collectionsGifts);
            }
        }
        
        public ActionResult Create(int id)
        {
                ViewBag.collectId = id;

                return View();      
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? id, [Bind(Include = "Id,Name")] CollectGift collectGift)
        {
            using (var collectService = new CollectsService())
            {
                if (ModelState.IsValid)
                {
                    collectGift.UserId = GetUserId();
                    collectGift.CollectId = id;
                    collectService.CollectGiftAdd(collectGift);

                    return RedirectToAction("Details", "Collects", new { id = id });
                }

                return View(collectGift);
            }
        }
        
        public ActionResult Delete(int id)
        {
            using (var collectService = new CollectsService())
            {
                var collectGift = collectService.GetCollectGift(id);
                return View(collectGift);
            } 
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var collectService = new CollectsService())
            {
                collectService.CollectGiftDelete(id);
                return RedirectToAction("Index");
            }
        }
    }
}

BirthdayApp/Controllers/CollectUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppModels;
using BirthdayApp.Models;
using Microsoft.AspNet.Identity;
using BirthdayApp.AppService;

namespace BirthdayApp.Controllers
{
    public class CollectUsersController : CommonController
    {
        public ActionResult Index(int id)
        {
            using (var collectService = new CollectsService())
            {
                using (var userService = new UsersService())
                {
                    if (!userService.IsOwner(GetUserId()))
                        return HttpNotFound();
                }

                ViewBag.ThisId = id;
                var collectUsers = collectService.GetCollectUserIndex(id);
                
                return View(collectUsers);
            }
        }

        public ActionResult GaveMoney(int id)
        {
            using (var collectService = new CollectsService())
            {
                collectService.GaveMoneyChange(id);

                int collectId = collectService.GetCollectId(id);

                return RedirectToAction("Index", new { id = collectId });
            }
        }

        public ActionResult Join(int id)
        {
            using (var collectService = new CollectsService())
            {
                var collectViewModel = collectService.GetCollectViewModel(id, GetUserId());
                return View(collectViewModel);
            }
        }

        [HttpPost, ActionName("Join")]
        [ValidateAntiForgeryToken]
        public ActionResult JoinConfirmed(int id)
        {
            using (var collectService = new CollectsService())
            {
                int userId = GetUserId();
                var collectUser = collectService.GetCollectUser(id);

                if (ModelState.IsValid)
                {
                    collectService.JoinConfirmed(id, GetUserId());

                    return RedirectToAction("Details", "Collects" , new { id = id });
                }
            }

            return HttpNotFound();
        }
        
        public ActionResult Leave(int id)
        {
            using (var collectService = new CollectsService())
            {
                var collectViewModel = collectService.GetCollectViewModel(id,GetUserId());
                return View(collectViewModel);
            }
        }

        [HttpPost, ActionName("Leave")]
        [ValidateAntiForgeryToken]
        public ActionResult LeaveConfirmed(int id)
        {
            using (var collectService = new CollectsService())
            {
                collectService.LeaveConfirmed(id, GetUserId());
                return RedirectToAction("Index", "Collects");
            }
        }
    }
}

BirthdayApp/Controllers/CollectUsersListBoxController.cs
using AppModels;
using BirthdayApp.AppService;
using BirthdayApp.Models;
using BirthdayApp.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace BirthdayApp.Controllers
{
    public class CollectUsersListBoxController : CommonController
    {
        public ActionResult Index(int id)
        {
            using (var collectService = new CollectsService())
            {
                var person = collectService.GetCollectUsersListBoxViewModel(id);
                return View(person);
            }
        }

        [HttpPost]
        public ActionResult Index(int id, CollectUsersListBoxViewModel person)
        {
            using (var collectService = new CollectsService())
            {
                var personPost = collectService.GetCollectUsersListBoxViewModelPost(id,person);
                return View(personPost);
            }
        }

    }
}

BirthdayApp/Controllers/CollectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppModels;
using BirthdayApp.Models;
using BirthdayApp.AppService;
using Microsoft.AspNet.Identity;
using BirthdayApp.ViewModels;
using System.Text;
using PagedList;

namespace BirthdayApp.Controllers
{
    public class CollectsController : CommonController
    {
        public ActionResult Index(int? page)
        {
            int userId = GetUserId();
            using (var collectService = new CollectsService())
            {
                var collections = collectService.AllCollectList(userId).Where(i => i.RecipientId != userId).OrderByDescending(i => i.DateOfAdd).ToList();

                int pageSize = 5;
                int pageNumber = (page ?? 1);
                return View(collections.ToPagedList(pageNumber, pageSize));
                //return View(collections);
            }
        }

        public ActionResult Details(int id)
        {
            using (var collectService = new CollectsService())
            {
                ViewBag.InCollect = collectService.IsCollectionsUser(id, GetUserId());
                var collectViewModel = collectService.GetCollectViewModel(id, GetUserId());
                return View(collectViewModel);
            }
        }

        [HttpPost]
        public ActionResult Details(int id, CollectViewModel model)
        {
            using (var collectService = new CollectsService())
            {
                ViewBag.InCollect = collectService.IsCollectionsUser(id, GetUserId());

                if (ModelState.IsValid)
                    collectService.ChangeRadioButtonChoose(id, GetUserId(), model.Gift.Id);

                var collectViewModel = collectService.GetCollectViewModel(id, GetUserId());
                return View(collectViewModel);
            }
        }

        public ActionResult UndoConfirm(int id)
        {
            using (var collectService = new CollectsService())
            {
                collectService.CollectConfirmChange(id, false);
            }

            return RedirectToAction("Details", "Collects", new { id = id });
        }

        public ActionResult Confirm(int id)
        {
            using (var collectService = new CollectsService())
            {
                var collectViewModel = collectService.GetCollectViewModel(id, GetUserId());

                using (var userService = new UsersService())
                {
                    if (!userService.IsAdmin(GetUserId()))
                    {
                        if (!collectService.IsCollectionsUser(id, GetUserId()))
                        {
                            return HttpNotFound();
                        }
                    }
                }

                if (collectService.CounterCollectionsGifts(id) == 0)
                    ViewBag.MustChooseItem = "Musisz wybrać któryś z prezentów !";

                return View(collectViewModel);
            }
        }


        [HttpPost]
        public ActionResult Confirm(int id, string uniqueRadio, string fname, CollectViewModel model)
        {
            using (var collectService = new CollectsService())
            {
                try
                {
                    int selectedId = Int32.Parse(model.Gift.Id);
                    if (ModelState.IsValid)
                    {
                        collectService.ChangeRadioButtonChoose(id, GetUserId(), model.Gift.Id);
                    }
                    collectService.CollectAmountChange(id, model.Amount);
                    collectService.CollectConfirmChange(id, true);

                    //Send Email
                    using (var userService = new UsersService())
                    {
                        var collect = collectService.GetCollect(id);

                        collectService.SendEmailsConfirm(userService.GetUserIndex().Where(i => i.Id != collect.RecipientId).ToList(), collect);
                    }

                    return RedirectToAction("Details", "Collects", new { id = id });
                }
                catch (NullReferenceException)
                {
                    ViewBag.MustChooseItem = "Musisz wybrać jakikolwiek prezent !";
                }

                var collectViewModel = collectService.GetCollectViewModel(id, GetUserId());

                return View(collectViewModel);
            }
        }

        public ActionResult Create()
        {
            using (var collectService = new CollectsService())
            {
                int userId = GetUserId();
                var modelUsersWithoutThisUser = collectService.AllMyUserList().Where(i => i.Id != userId);
                ViewBag.RecipientId = new SelectList(modelUsersWithoutThisUser, "Id", "Name");
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,RecipientId,Name,Description,Amount,DateOfInitiative")] Collect collect)
        {
            if (ModelState.IsValid)
            {
                using (var collectService = new CollectsService())
                {
                    collect.OwnerId = GetUserId();
                    collectService.CollectAdd(collect);

                    var newCollectionUsers = new CollectUser();
                    newCollectionUsers.UserId = collect.OwnerId;
                    newCollectionUsers.CollectId = collect.Id;
                    collectService.CollectUserAdd(newCollectionUsers);

                    //Send Email
                    using (var userService = new UsersService())
                    {
                        collectService.SendEmailsCreate(userService.GetUserIndex().Where(i => i.Id != collect.RecipientId).ToList(), collect);
                    }

                    return RedirectToAction("Details", "Collects", new { id = collect.Id });
                }
            }

            using (var collectService = new CollectsService())
            {
                ViewBag.OwnerId = new SelectList(collectService.AllMyUserList(), "Id", "Name", collect.OwnerId);
                ViewBag.RecipientId = new SelectList(collectService.AllMyUserList(), "Id", "Name", collect.RecipientId);
                return View(collect);
            }
        }

        public ActionResult Edit(int id)
        {
            using (var collectService = new CollectsService())
                return View(collectService.GetCollect(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,OwnerId,RecipientId,Name,Description,Amount,DateOfInitiative,IsActive")] Collect collect)
        {
            if (ModelState.IsValid)
            {
                using (var collectService = new CollectsService())
                    collectService.CollectChange(collect);

                return RedirectToAction("Index");
            }
            return View(collect);
        }

        public ActionResult Delete(int id)
        {
            using (var collectService = new CollectsService())
                return View(collectService.GetCollect(id));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (var collectService = new CollectsService())
            {
                collectService.CollectUnActive(id);
                return RedirectToAction("Index");
            }
        }
    }
}

BirthdayApp/Views/Collects/Delete.cshtml
@model AppModels.Collect

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Collect</h4>
    <hr />
    <dl class="dl-horizontal">

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.OwnerId)
        @Html.HiddenFor(model => model.RecipientId)
        @Html.HiddenFor(model => model.DateOfInitiative)
        @Html.HiddenFor(model => model.IsActive)

        @*<dt>
            @Html.DisplayNameFor(model => model.Owner.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Recipient.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Recipient.Name)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BirthdayApp/Views/Collects/Details.cshtml
@model BirthdayApp.ViewModels.CollectViewModel

<link href="~/CSSstyle/mystyle.css" rel="stylesheet" />
<link href="~/Content/icheck-bootstrap.css" rel="stylesheet" />
<link href="~/Content/icheck-bootstrap.min.css" rel="stylesheet" />

<div class="row">
    <div class="col-sm-12">

        @{
            ViewBag.Title = "Informacje o zbiórce";
        }

        <h2>@ViewBag.Title</h2>


        <div>

            @if(ViewBag.InCollect)
            {

            

            <hr />

            <div class="row">
                <div class="col-sm-2">
                    <center>
                        @if (Model.IsConfirmed)
                        {
                            <img src="~/Images/success.png" />
                        }
                        else
                        {
                            <img src="~/Images/info.png" />
                        }
                        </center>
</div>

                <div class="col-sm-10">
                    <center>
                        @if (Model.IsConfirmed)
            {
                            <p><b><font color="red">Zbiórka została zatwierdzona przez założyciela zbiórki!</font></b></p>
                            @Html.Raw("")
                            <br />
                            @Html.Raw("Wybrany prezent: ")
                            <b>
                                @Html.Raw(Model.GiftName)
                            </b>
                            <br />
                            @Html.Raw("Łączna kwota: ")
                            @Html.Raw(Model.Amount + " PLN")
                            <br />
                            @Html.Raw("Kwota na jedną osobę: ")
                            @Html.Raw(Model.AmountPerPerson + " PLN")
                        }
                        else
                        {
                            <p><b><font color="red">Zbiórka jest otwarta</font></b></p>
                        }
                    </center>
                </div>
                </div>


                <br />
            }
                <hr />


            <p><b>Szczegóły zbiórki:</b></p>
                <table class="table table-bordered">
                    <tr>
                        <td>
                            <b>Nazwa zbiórki:</b>
                        </td>
                        <td>
                            <b>Opis zbiórki:</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.DisplayFor(model => model.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.Description)
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <b>Zbiórkę założył:</b>
                        </td>
                        <td>
                            <b>Zbieramy na prezent dla:</b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.DisplayFor(model => model.OwnerName)
                        </td>
                        <td>
                            @Html.DisplayFor(model => model.RecipientName)
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <b>Szacowana kwota prezentu to:</b>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>
                            @Html.DisplayFor(model => model.Amount)
                            @Html.Raw(" PLN")
                        </td>
                        <td></td>
                    </tr>
                </table>

@if (ViewBag.InCollect)
{
                <hr />

                using (Html.BeginForm())
                {
                    <p><b>Wybierz jeden z prezentów:</b></p>

                    <table class="table table-bordered">
                        <tr>
                            <td>
                                <ol class="Opt">
                                    <li class="Opt">
                                        <div class="radio icheck-primary">
                                            @Html.RadioButtonFor(model => model.Gift.Id, "0", new { id = 0, @checked = true, onchange = "this.form.submit();" })
                                            <label for=0>Nie wybieram prezentu</label>
                                        </div>
                                    </li>

                                    @foreach (var item in Model.RadioGiftItems)
                                    {
                                        <li class="Opt">
                                            <div class="radio icheck-primary">
                                                @if (item.Checked)
                                                {
                                                    @Html.RadioButtonFor(model => model.Gift.Id, item.Id, new { id = item.Id, @checked = true, onchange = "this.form.submit();" })
                                                }
                                                else
                                                {
                                                    @Html.RadioButtonFor(model => model.Gift.Id, item.Id, new { id = item.Id, onchange = "this.form.submit();" })
                                                }
                                                <label for=@item.Id>@item.Name (@item.Rating)</label>
                                            </div>
                                        </li>
                                    }

                                </ol>
                                @Html.ActionLink("Dodaj własną propozycję prezentu", "Create", "CollectGifts", new { id = Model.Id }, null)


                            </td>
                        </tr>
                    </table>

                }


                <hr />



            <p><b>Użytkownicy którzy są aktualnie w zbiórce:</b></p>

                <table class="table table-bordered">
                    <tr>
                        <td><b>Użytkownik</b></td>
                        <td><b>Czy zapłacił?</b></td>
                    </tr>

                    @foreach (var item in Model.Users)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td>
                                @if (item.GaveMoney)
                                {
                                    <img src="~/Images/tick-yes.png" />
                                }
                                else
                                {
                                    <img src="~/Images/tick-no.png" />
                                }

                            </td>
                        </tr>
                    }


                </table>


                <br />
                @*@Html.ActionLink("Opuść zbiórkę", "Leave", "CollectUsers", new { id = Model.Id }, null)*@

            <input type="button" class="btn btn-danger" value="Opuść zbiórkę" onclick="location.href = '@Url.Action("Leave", "CollectUsers", new { id = Model.Id }, Request.Url.Scheme)';">

                if (Model.OwnerId == Model.UserId)
                {
                    <hr />
                    <p><b>Sekcja założyciela zbiórki:</b></p>
                        @Html.ActionLink("Edytuj zbiórkę", "Edit", new { id = Model.Id })
                        <br />
                        @*@Html.ActionLink("Zarządzaj użytkownikami zbiórki", "Index", "CollectUsersListBox", new { id = Model.Id }, null)
                        <br />*@
                if (!Model.IsConfirmed)
                {
                        @Html.ActionLink("Zarządzaj prezentami", "Index", "CollectGifts", new { id = Model.Id }, null)
                        <br />
                }
                else
                {
                        @Html.ActionLink("Zarządzaj tym kto zapłacił", "Index", "CollectUsers", new { id = Model.Id }, null)
                        <br />
                }
                        <br />
                    if (Model.PossibilityEditCollectGift)
                    {
                        @*@Html.ActionLink("Finalizacja zbiórki", "Confirm", "Collects", new { id = Model.Id }, null)*@
                        <input type="button" class="btn btn-success" value="Finalizacja zbiórki" onclick="location.href = '@Url.Action("Confirm", "Collects", new { id = Model.Id }, Request.Url.Scheme)';">
                    }
                    else
                    {
                        @Html.Raw("Nie można wprowadzać zmian dotyczących zrzutki gdy ktokolwiek zapłacił już za prezent!")
                    }
                    <br />
                }


        }

                <hr />


            </div>



                @*<p>
                    @Html.ActionLink("Wróć do listy", "Index")
                </p>*@
        <input type="button" class="btn btn-primary" value="Wróć do listy" onclick="location.href = '@Url.Action("Index", "Collects", null, Request.Url.Scheme)';">

            </div>
        </div>


@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    @if (Model.IsConfirmed)
    {
        <script>
            $(document).ready(function () {
                $(':radio:not(:checked)').attr('disabled', true);
            });
        </script>
    }
}

BirthdayApp/Views/Collects/Index.cshtml
@model PagedList.IPagedList<BirthdayApp.ViewModels.CollectListItemViewModel>
@using PagedList.Mvc;

@*@model IEnumerable<BirthdayApp.ViewModels.CollectListItemViewModel>*@

@{
    ViewBag.Title = "Lista zbiórek";
}

<h2>@ViewBag.Title</h2>
<p>
    @Html.ActionLink("Utwórz nową zbiórkę", "Create")
</p>

    <table class="table">
        <tr>
            <th>
                Założyciel zbiórki
            </th>
            <th>
                Zbieramy dla
            </th>
            <th>
                Nazwa zbiórki
            </th>
            <th>
                Kwota
            </th>
            <th>
                Data inicjatywy
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RecipientName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                    @Html.Raw("PLN")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfInitiative)
                </td>
                <td>
                    @if (item.OwnerId == item.UserId)
                    {
                        @Html.ActionLink("Edytuj", "Edit", new { id = item.Id })
                        @Html.Raw(" | ")
                        @Html.ActionLink("Usuń", "Delete", new { id = item.Id })
                        <br />
                    }

                    @if (item.YoureInCollection)
                    {
                            <div class="DetailsBackground">
                                @Html.ActionLink("Szczegóły zbiórki", "Details", new { id = item.Id })
                            </div>
                    }
                    else
                    {
                        @Html.ActionLink("O zbiórce", "Details", new { id = item.Id })
                        @Html.Raw(" | ")
                        @Html.ActionLink("Dołącz do zbiórki", "Join", "CollectUsers", new { id = item.Id }, null)
                    }
                    
                    
            </td>
            </tr>
        }

    </table>

<br />
    Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
                    new { page }))



@section Scripts
{
    <style>
        .DetailsBackground {
            color: black;
            background-color: lightgreen;
        }
    </style>
}